package it.unibo.pps.view

import java.awt.Color

object ViewConstants:
  val NUM_CARS = 4
  val FRAME_WIDTH = 1296
  val FRAME_HEIGHT = 810
  val STARTING_POS_FRAME_WIDTH = (FRAME_WIDTH * 0.35).toInt
  val STARTING_POS_FRAME_HEIGHT = (FRAME_HEIGHT * 0.45).toInt
  val STARTING_POS_PANEL_WIDTH = (FRAME_WIDTH * 0.4).toInt
  val STARTING_POS_PANEL_HEIGHT = (FRAME_HEIGHT * 0.4).toInt
  val CANVAS_WIDTH = (FRAME_WIDTH * 0.70).toInt
  val CANVAS_HEIGHT = (FRAME_HEIGHT * 0.6).toInt
  val CHART_WIDTH = (FRAME_WIDTH * 0.25).toInt
  val CHART_HEIGHT = 300
  val CHART_PANEL_WIDTH = (FRAME_WIDTH * 0.28).toInt
  val CHART_PANEL_HEIGHT = (FRAME_HEIGHT * 0.9).toInt
  val BUTTONS_PANEL_HEIGHT = (FRAME_HEIGHT * 0.05).toInt
  val STANDING_PANEL_HEIGHT = (FRAME_HEIGHT * 0.29).toInt
  val STANDING_SUBPANEL_HEIGHT = (STANDING_PANEL_HEIGHT / NUM_CARS) - 7
  val PADDING_LABEL_WIDTH = 30
  val CAR_SELECT_PANEL_WIDTH = (FRAME_WIDTH * 0.48).toInt
  val CAR_SELECT_PANEL_HEIGHT = (FRAME_HEIGHT * 0.65).toInt
  val VERTICAL_SCROLLBAR_AS_NEEDED = 22
  val TURN_START_ANGLE = 270
  val TURN_END_ANGLE = 180
  val CAR_DIAMETER = 12
  val BUTTON_NOT_SELECTED = Color(238, 238, 238)
  val CAR_NAMES = Map(0 -> "Ferrari", 1 -> "Mercedes", 2 -> "Red Bull", 3 -> "McLaren")
  
