package it.unibo.pps.view

object ViewConstants:
  val FRAME_WIDTH = 1296
  val FRAME_HEIGHT = 810
  val CANVAS_WIDTH = (FRAME_WIDTH * 0.7).toInt
  val CANVAS_HEIGHT = (FRAME_HEIGHT * 0.7).toInt
  val CHART_WIDTH = (FRAME_WIDTH * 0.25).toInt
  val CHART_HEIGHT = 300
  val VERTICAL_SCROLLBAR_AS_NEEDED = 22
  val CHART_PANEL_WIDTH = (FRAME_WIDTH * 0.3).toInt
  val CHART_PANEL_HEIGHT = (FRAME_HEIGHT * 0.7).toInt
  val TURN_START_ANGLE = 270
  val TURN_END_ANGLE = 180
  val CAR_DIAMETER = 12
